version: "3.8"

services:
  # Redis Cache
  redis:
    image: redis:7-alpine
    container_name: skycast-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  # FastAPI Backend
  backend:
    build:
      context: ./backend
      dockerfile: ../cloud/Dockerfile.backend
    container_name: skycast-backend
    ports:
      - "8000:8000"
    environment:
      - REDIS_URL=redis://redis:6379
      - ENVIRONMENT=development
    env_file:
      - ./backend/.env
    depends_on:
      redis:
        condition: service_healthy
    volumes:
      - ./backend:/app
      - ./ml/models:/app/models
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload

  # Next.js Frontend
  frontend:
    build:
      context: ./frontend
      dockerfile: ../cloud/Dockerfile.frontend
    container_name: skycast-frontend
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_API_URL=http://backend:8000
    env_file:
      - ./frontend/.env.local
    depends_on:
      - backend
    volumes:
      - ./frontend:/app
      - /app/node_modules
      - /app/.next
    command: npm run dev

volumes:
  redis_data:
